version: "2"
services:
  app:
    container_name: nodedrop
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: nodedrop-mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"